In [77]:
import pandas as pd

In [78]:
pd.set_option('display.max_columns', None)

In [79]:
df = pd.read_parquet('../data/us_accidents.parquet')
df

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Street,City,County,State,Zipcode,Country,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.010,Right lane blocked due to accident on I-70 Eas...,I-70 E,Dayton,Montgomery,OH,45424,US,US/Eastern,KFFO,2016-02-08 05:58:00,36.9,NaN,91.0,29.68,10.0,Calm,NaN,0.02,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.010,Accident on Brice Rd at Tussing Rd. Expect del...,Brice Rd,Reynoldsburg,Franklin,OH,43068-3402,US,US/Eastern,KCMH,2016-02-08 05:51:00,37.9,NaN,100.0,29.65,10.0,Calm,NaN,0.00,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.010,Accident on OH-32 State Route 32 Westbound at ...,State Route 32,Williamsburg,Clermont,OH,45176,US,US/Eastern,KI69,2016-02-08 06:56:00,36.0,33.3,100.0,29.67,10.0,SW,3.5,NaN,Overcast,False,False,False,False,False,False,False,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.010,Accident on I-75 Southbound at Exits 52 52B US...,I-75 S,Dayton,Montgomery,OH,45417,US,US/Eastern,KDAY,2016-02-08 07:38:00,35.1,31.0,96.0,29.64,9.0,SW,4.6,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.010,Accident on McEwen Rd at OH-725 Miamisburg Cen...,Miamisburg Centerville Rd,Dayton,Montgomery,OH,45459,US,US/Eastern,KMGY,2016-02-08 07:53:00,36.0,33.3,89.0,29.65,6.0,SW,3.5,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7728389,A-7777757,Source1,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,33.99888,-117.37094,0.543,At Market St - Accident.,Pomona Fwy E,Riverside,Riverside,CA,92501,US,US/Pacific,KRAL,2019-08-23 17:53:00,86.0,86.0,40.0,28.92,10.0,W,13.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
7728390,A-7777758,Source1,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,32.76555,-117.15363,0.338,At Camino Del Rio/Mission Center Rd - Accident.,I-8 W,San Diego,San Diego,CA,92108,US,US/Pacific,KMYF,2019-08-23 18:53:00,70.0,70.0,73.0,29.39,10.0,SW,6.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
7728391,A-7777759,Source1,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,33.77740,-117.85727,0.561,At Glassell St/Grand Ave - Accident. in the ri...,Garden Grove Fwy,Orange,Orange,CA,92866,US,US/Pacific,KSNA,2019-08-23 18:53:00,73.0,73.0,64.0,29.74,10.0,SSW,10.0,0.00,Partly Cloudy,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
7728392,A-7777760,Source1,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,33.98311,-118.39565,0.772,At CA-90/Marina Fwy/Jefferson Blvd - Accident.,San Diego Fwy S,Culver City,Los Angeles,CA,90230,US,US/Pacific,KSMO,2019-08-23 18:51:00,71.0,71.0,81.0,29.62,10.0,SW,8.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
7728393,A-7777761,Source1,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,34.13736,-117.23934,0.537,At Highland Ave/Arden Ave - Accident.,CA-210 W,Highland,San Bernardino,CA,92346,US,US/Pacific,KSBD,2019-08-23 20:50:00,79.0,79.0,47.0,28.63,7.0,SW,7.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day

In [80]:
df.drop(columns=['ID', 'Source', 'Distance(mi)', 'End_Time', 'Duration', 'End_Lat', 'End_Lng', 'Description','Country', 'Street', 'Weather_Timestamp', 'Timezone', 'Zipcode'], inplace = True , errors='ignore')

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 34 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Severity               int64
 1   Start_Time             object
 2   Start_Lat              float64
 3   Start_Lng              float64
 4   City                   object
 5   County                 object
 6   State                  object
 7   Airport_Code           object
 8   Temperature(F)         float64
 9   Wind_Chill(F)          float64
 10  Humidity(%)            float64
 11  Pressure(in)           float64
 12  Visibility(mi)         float64
 13  Wind_Direction         object
 14  Wind_Speed(mph)        float64
 15  Precipitation(in)      float64
 16  Weather_Condition      object
 17  Amenity                bool
 18  Bump                   bool
 19  Crossing               bool
 20  Give_Way               bool
 21  Junction               bool
 22  No_Exit                bool
 23  Railway                bool
 24  Roundabout             bool
 25  Station                bool
 26  Stop                   bool
 27  Traffic_Calming        bool
 28  Traffic_Signal         bool
 29  Turning_Loop           bool
 30  Sunrise_Sunset         object
 31  Civil_Twilight         object
 32  Nautical_Twilight      object
 33  Astronomical_Twilight  object
dtypes: bool(13), float64(9), int64(1), object(11)
memory usage: 1.3+ GB

In [82]:
df.head()

,Severity,Start_Time,Start_Lat,Start_Lng,City,County,State,Airport_Code,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,3,2016-02-08 05:46:00,39.865147,-84.058723,Dayton,Montgomery,OH,KFFO,36.9,NaN,91.0,29.68,10.0,Calm,NaN,0.02,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night
1,2,2016-02-08 06:07:59,39.928059,-82.831184,Reynoldsburg,Franklin,OH,KCMH,37.9,NaN,100.0,29.65,10.0,Calm,NaN,0.00,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Day
2,2,2016-02-08 06:49:27,39.063148,-84.032608,Williamsburg,Clermont,OH,KI69,36.0,33.3,100.0,29.67,10.0,SW,3.5,NaN,Overcast,False,False,False,False,False,False,False,False,False,False,False,True,False,Night,Night,Day,Day
3,3,2016-02-08 07:23:34,39.747753,-84.205582,Dayton,Montgomery,OH,KDAY,35.1,31.0,96.0,29.64,9.0,SW,4.6,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day
4,2,2016-02-08 07:39:07,39.627781,-84.188354,Dayton,Montgomery,OH,KMGY,36.0,33.3,89.0,29.65,6.0,SW,3.5,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day

In [112]:
df_airport = pd.read_parquet('../data/iata-icao-us.parquet')
df_airport

,country_code,region_name,iata,icao,airport,latitude,longitude
6803,US,Alabama,AIV,KAIV,George Downer Airport,33.1065,-88.1978
6804,US,Alabama,ALX,KALX,Thomas C. Russell Field,32.9147,-85.9630
6805,US,Alabama,ANB,KANB,Anniston Regional Airport,33.5882,-85.8581
6806,US,Alabama,ASN,KASN,Talladega Municipal Airport,33.5699,-86.0509
6807,US,Alabama,AUO,KAUO,Auburn University Regional Airport,32.6151,-85.4340
...,...,...,...,...,...,...,...
8832,US,Wyoming,SAA,KSAA,Shively Field,41.4449,-106.8240
8833,US,Wyoming,SHR,KSHR,Sheridan County Airport,44.7692,-106.9800
8834,US,Wyoming,THP,KTHP,Hot Springs County-Thermopolis Municipal Airport,43.7136,-108.3900
8835,US,Wyoming,TOR,KTOR,Torrington Municipal Airport,42.0645,-104.1530
8836,US,Wyoming,WRL,KWRL,Worland Municipal Airport,43.9657,-107.9510

In [113]:
df_airport.drop(columns=['country_code', 'region_name', 'icao'], inplace=True, errors='ignore')

In [ ]:
df_airport

In [83]:
df_airport = pd.read_parquet('../data/airports-code-us.parquet')
df_airport

,column_1,airport_name,city_name,country_name,country_code,latitude,longitude,world_area_code,city_name_geo_name_id,country_name_geo_name_id,coordinates
0,HKS,Hawkins Field,Jackson,United States,US,32.333611,-90.222222,67,5828648,6252001,b'\x01\x01\x00\x00\x00\xe9\x9c\x9f\xe28\x8eV\x...
1,CIN,Carroll,Carroll,United States,US,42.050000,-94.783333,67,4850478,6252001,"b'\x01\x01\x00\x00\x00*8\xbc ""\xb2W\xc0fffff\x..."
2,KOA,Kona International Airport,"Kona, HI",United States,US,19.738889,-156.045556,67,\N,6252001,"b""\x01\x01\x00\x00\x00_D\xdb1u\x81c\xc0\xc8_Z\..."
3,GNG,Gooding,Gooding,United States,US,42.916667,-114.783333,67,5594307,6252001,"b'\x01\x01\x00\x00\x00*8\xbc ""\xb2\\\xc0E)!XUuE@'"
4,EYW,International,Key West,United States,US,24.550000,-81.766667,67,4160812,6252001,b'\x01\x01\x00\x00\x00\t\xfbv\x12\x11qT\xc0\xc...
...,...,...,...,...,...,...,...,...,...,...,...
2232,MXO,Municipal,Monticello,United States,US,40.650000,15.016667,67,5543377,6252001,b'\x01\x01\x00\x00\x00I\xd8\xb7\x93\x88\x08.@3...
2233,CBF,Municipal,Council Bluffs,United States,US,41.266667,-95.866667,67,4852832,6252001,b'\x01\x01\x00\x00\x00pa\xddxw\xf7W\xc0\x12\xf...
2234,SMK,St Michael,St Michael,United States,US,63.483333,-162.016667,67,\N,6252001,b'\x01\x01\x00\x00\x00\x85};\x89\x88@d\xc0\xee...
2235,XMD,Madison,Madison,United States,US,44.000000,-97.116667,67,5261457,6252001,b'\x01\x01\x00\x00\x00pa\xddxwGX\xc0\x00\x00\x...
2236,MML,Municipal-Ryan Field,Marshall,United States,US,44.444167,-95.820000,67,5261952,6252001,b'\x01\x01\x00\x00\x00\x14\xaeG\xe1z\xf4W\xc01...

In [84]:
df_airport.rename(columns={'column_1': 'Airport_Code'}, inplace=True, errors='ignore')

In [85]:
df_airport.drop(columns=['country_name', 'country_code', 'coordinates', 'country_name_geo_name_id', 'city_name_geo_name_id', 'world_area_code'], inplace=True, errors='ignore')

In [86]:
df_airport

,Airport_Code,airport_name,city_name,latitude,longitude
0,HKS,Hawkins Field,Jackson,32.333611,-90.222222
1,CIN,Carroll,Carroll,42.050000,-94.783333
2,KOA,Kona International Airport,"Kona, HI",19.738889,-156.045556
3,GNG,Gooding,Gooding,42.916667,-114.783333
4,EYW,International,Key West,24.550000,-81.766667
...,...,...,...,...,...
2232,MXO,Municipal,Monticello,40.650000,15.016667
2233,CBF,Municipal,Council Bluffs,41.266667,-95.866667
2234,SMK,St Michael,St Michael,63.483333,-162.016667
2235,XMD,Madison,Madison,44.000000,-97.116667
2236,MML,Municipal-Ryan Field,Marshall,44.444167,-95.820000

In [87]:
df['Airport_Code'] = df['Airport_Code'].str.replace('^K', '', regex=True)

In [88]:
df = df.merge(df_airport, how='left', left_on='Airport_Code', right_on='Airport_Code', suffixes=('', '_airport'))

In [89]:
df

,Severity,Start_Time,Start_Lat,Start_Lng,City,County,State,Airport_Code,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,airport_name,city_name,latitude,longitude
0,3,2016-02-08 05:46:00,39.865147,-84.058723,Dayton,Montgomery,OH,FFO,36.9,NaN,91.0,29.68,10.0,Calm,NaN,0.02,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,Patterson Afb,Dayton,39.826111,-84.048333
1,2,2016-02-08 06:07:59,39.928059,-82.831184,Reynoldsburg,Franklin,OH,CMH,37.9,NaN,100.0,29.65,10.0,Calm,NaN,0.00,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Day,Port Columbus Intl,Columbus,40.000000,-82.883333
2,2,2016-02-08 06:49:27,39.063148,-84.032608,Williamsburg,Clermont,OH,I69,36.0,33.3,100.0,29.67,10.0,SW,3.5,NaN,Overcast,False,False,False,False,False,False,False,False,False,False,False,True,False,Night,Night,Day,Day,NaN,NaN,NaN,NaN
3,3,2016-02-08 07:23:34,39.747753,-84.205582,Dayton,Montgomery,OH,DAY,35.1,31.0,96.0,29.64,9.0,SW,4.6,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day,James Cox Dayton Intl,"Dayton, Oh",39.750000,-84.183333
4,2,2016-02-08 07:39:07,39.627781,-84.188354,Dayton,Montgomery,OH,MGY,36.0,33.3,89.0,29.65,6.0,SW,3.5,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day,Dayton-Wright Brothers Airport,Dayton,39.588889,-84.224722
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7728389,2,2019-08-23 18:03:25,34.002480,-117.379360,Riverside,Riverside,CA,RAL,86.0,86.0,40.0,28.92,10.0,W,13.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,Riverside Municipal,Riverside,33.950000,-117.433333
7728390,2,2019-08-23 19:11:30,32.766960,-117.148060,San Diego,San Diego,CA,MYF,70.0,70.0,73.0,29.39,10.0,SW,6.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,Montgomery Field,San Diego,32.800000,-117.133333
7728391,2,2019-08-23 19:00:21,33.775450,-117.847790,Orange,Orange,CA,SNA,73.0,73.0,64.0,29.74,10.0,SSW,10.0,0.00,Partly Cloudy,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day,John Wayne,"Santa Ana, CA",33.666667,-117.866667
7728392,2,2019-08-23 19:00:21,33.992460,-118.403020,Culver City,Los Angeles,CA,SMO,71.0,71.0,81.0,29.62,10.0,SW,8.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,Santa Monica,Santa Monica,34.015833,-118.450000
7728393,2,2019-08-23 18:52:06,34.133930,-117.230920,Highland,San Bernardino,CA,SBD,79.0,79.0,47.0,28.63,7.0,SW,7.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,Norton Afb,San Bernardino,34.095278,-117.235000

In [90]:
df[['Severity', 'Start_Time', 'Start_Lat', 'Start_Lng', 'City', 'County', 'State', 'Airport_Code', 'airport_name', 'latitude', 'longitude']]

,Severity,Start_Time,Start_Lat,Start_Lng,City,County,State,Airport_Code,airport_name,latitude,longitude
0,3,2016-02-08 05:46:00,39.865147,-84.058723,Dayton,Montgomery,OH,FFO,Patterson Afb,39.826111,-84.048333
1,2,2016-02-08 06:07:59,39.928059,-82.831184,Reynoldsburg,Franklin,OH,CMH,Port Columbus Intl,40.000000,-82.883333
2,2,2016-02-08 06:49:27,39.063148,-84.032608,Williamsburg,Clermont,OH,I69,NaN,NaN,NaN
3,3,2016-02-08 07:23:34,39.747753,-84.205582,Dayton,Montgomery,OH,DAY,James Cox Dayton Intl,39.750000,-84.183333
4,2,2016-02-08 07:39:07,39.627781,-84.188354,Dayton,Montgomery,OH,MGY,Dayton-Wright Brothers Airport,39.588889,-84.224722
...,...,...,...,...,...,...,...,...,...,...,...
7728389,2,2019-08-23 18:03:25,34.002480,-117.379360,Riverside,Riverside,CA,RAL,Riverside Municipal,33.950000,-117.433333
7728390,2,2019-08-23 19:11:30,32.766960,-117.148060,San Diego,San Diego,CA,MYF,Montgomery Field,32.800000,-117.133333
7728391,2,2019-08-23 19:00:21,33.775450,-117.847790,Orange,Orange,CA,SNA,John Wayne,33.666667,-117.866667
7728392,2,2019-08-23 19:00:21,33.992460,-118.403020,Culver City,Los Angeles,CA,SMO,Santa Monica,34.015833,-118.450000
7728393,2,2019-08-23 18:52:06,34.133930,-117.230920,Highland,San Bernardino,CA,SBD,Norton Afb,34.095278,-117.235000

In [91]:
df[df['airport_name'].isna() & df['Airport_Code'].notna()]

,Severity,Start_Time,Start_Lat,Start_Lng,City,County,State,Airport_Code,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,airport_name,city_name,latitude,longitude
2,2,2016-02-08 06:49:27,39.063148,-84.032608,Williamsburg,Clermont,OH,I69,36.0,33.3,100.0,29.67,10.0,SW,3.5,NaN,Overcast,False,False,False,False,False,False,False,False,False,False,False,True,False,Night,Night,Day,Day,NaN,NaN,NaN,NaN
10,3,2016-02-08 08:14:42,39.952812,-83.119293,Columbus,Franklin,OH,TZR,35.6,30.7,93.0,29.64,5.0,WNW,5.8,NaN,Rain,False,False,True,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
53,3,2016-02-09 07:03:20,39.976398,-83.119225,Columbus,Franklin,OH,TZR,21.2,8.3,93.0,29.66,1.5,WSW,13.8,NaN,Light Snow,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day,NaN,NaN,NaN,NaN
55,2,2016-02-09 07:04:58,39.232578,-84.159286,Goshen,Clermont,OH,I69,21.0,10.6,93.0,29.73,2.5,WSW,9.2,NaN,Light Snow,False,False,False,False,False,False,False,False,False,True,False,False,False,Night,Night,Day,Day,NaN,NaN,NaN,NaN
64,2,2016-02-09 08:10:20,39.834282,-82.743820,Carroll,Fairfield,OH,LHQ,21.9,10.4,85.0,29.70,0.8,SW,11.5,0.0,Light Snow,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7728352,4,2019-08-23 17:01:58,40.374860,-120.399344,Susanville,Lassen,CA,RTS,90.0,90.0,17.0,24.91,10.0,VAR,7.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
7728353,4,2019-08-23 17:01:58,40.370829,-120.400948,Susanville,Lassen,CA,RTS,90.0,90.0,17.0,24.91,10.0,VAR,7.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
7728357,3,2019-08-23 04:04:48,34.075790,-118.276680,Los Angeles,Los Angeles,CA,CQT,67.0,67.0,79.0,29.62,7.0,CALM,0.0,0.0,Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,NaN,NaN,NaN,NaN
7728361,2,2019-08-23 12:52:31,34.023790,-118.276390,Los Angeles,Los Angeles,CA,CQT,81.0,81.0,49.0,29.66,8.0,CALM,0.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
7728364,2,2019-08-23 13:42:50,34.070610,-118.263910,Los Angeles,Los Angeles,CA,CQT,82.0,82.0,47.0,29.65,9.0,CALM,0.0,0.0,Fair,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN

In [92]:
df[df['airport_name'].isna() & df['Airport_Code'].notna()]['Airport_Code'].value_counts()

Airport_Code
CQT    118332
MCJ    101786
LOM     45110
JQF     32529
DMA     27582
        ...
PAT         1
8D3         1
Y22         1
AVK         1
ICR         1
Name: count, Length: 877, dtype: int64

In [93]:
1488326 < 1808287

True

In [94]:
df_airport2 = pd.read_parquet('../data/iata-icao-us.parquet')
df_airport2

,country_code,region_name,iata,icao,airport,latitude,longitude
6803,US,Alabama,AIV,KAIV,George Downer Airport,33.1065,-88.1978
6804,US,Alabama,ALX,KALX,Thomas C. Russell Field,32.9147,-85.9630
6805,US,Alabama,ANB,KANB,Anniston Regional Airport,33.5882,-85.8581
6806,US,Alabama,ASN,KASN,Talladega Municipal Airport,33.5699,-86.0509
6807,US,Alabama,AUO,KAUO,Auburn University Regional Airport,32.6151,-85.4340
...,...,...,...,...,...,...,...
8832,US,Wyoming,SAA,KSAA,Shively Field,41.4449,-106.8240
8833,US,Wyoming,SHR,KSHR,Sheridan County Airport,44.7692,-106.9800
8834,US,Wyoming,THP,KTHP,Hot Springs County-Thermopolis Municipal Airport,43.7136,-108.3900
8835,US,Wyoming,TOR,KTOR,Torrington Municipal Airport,42.0645,-104.1530
8836,US,Wyoming,WRL,KWRL,Worland Municipal Airport,43.9657,-107.9510

In [95]:
df_airport2.rename(columns={'iata': 'Airport_Code', 'airport':'airport_name'}, inplace=True, errors='ignore')

In [96]:
df_airport2.drop(columns=['country_code', 'region_name','icao'], inplace=True, errors='ignore')

In [97]:
df_airport2

,Airport_Code,airport_name,latitude,longitude
6803,AIV,George Downer Airport,33.1065,-88.1978
6804,ALX,Thomas C. Russell Field,32.9147,-85.9630
6805,ANB,Anniston Regional Airport,33.5882,-85.8581
6806,ASN,Talladega Municipal Airport,33.5699,-86.0509
6807,AUO,Auburn University Regional Airport,32.6151,-85.4340
...,...,...,...,...
8832,SAA,Shively Field,41.4449,-106.8240
8833,SHR,Sheridan County Airport,44.7692,-106.9800
8834,THP,Hot Springs County-Thermopolis Municipal Airport,43.7136,-108.3900
8835,TOR,Torrington Municipal Airport,42.0645,-104.1530
8836,WRL,Worland Municipal Airport,43.9657,-107.9510

In [98]:
df_airport2.columns

Index(['Airport_Code', 'airport_name', 'latitude', 'longitude'], dtype='object')

In [100]:
df.columns

Index(['Severity', 'Start_Time', 'Start_Lat', 'Start_Lng', 'City', 'County',
       'State', 'Airport_Code', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight', 'airport_name', 'city_name', 'latitude',
       'longitude'],
      dtype='object')

In [101]:
# Find rows in df where airport_name is NaN and Airport_Code is not NaN
missing_airport = df[df['airport_name'].isna() & df['Airport_Code'].notna()]

In [102]:
missing_airport

,Severity,Start_Time,Start_Lat,Start_Lng,City,County,State,Airport_Code,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,airport_name,city_name,latitude,longitude
2,2,2016-02-08 06:49:27,39.063148,-84.032608,Williamsburg,Clermont,OH,I69,36.0,33.3,100.0,29.67,10.0,SW,3.5,NaN,Overcast,False,False,False,False,False,False,False,False,False,False,False,True,False,Night,Night,Day,Day,NaN,NaN,NaN,NaN
10,3,2016-02-08 08:14:42,39.952812,-83.119293,Columbus,Franklin,OH,TZR,35.6,30.7,93.0,29.64,5.0,WNW,5.8,NaN,Rain,False,False,True,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
53,3,2016-02-09 07:03:20,39.976398,-83.119225,Columbus,Franklin,OH,TZR,21.2,8.3,93.0,29.66,1.5,WSW,13.8,NaN,Light Snow,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day,NaN,NaN,NaN,NaN
55,2,2016-02-09 07:04:58,39.232578,-84.159286,Goshen,Clermont,OH,I69,21.0,10.6,93.0,29.73,2.5,WSW,9.2,NaN,Light Snow,False,False,False,False,False,False,False,False,False,True,False,False,False,Night,Night,Day,Day,NaN,NaN,NaN,NaN
64,2,2016-02-09 08:10:20,39.834282,-82.743820,Carroll,Fairfield,OH,LHQ,21.9,10.4,85.0,29.70,0.8,SW,11.5,0.0,Light Snow,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7728352,4,2019-08-23 17:01:58,40.374860,-120.399344,Susanville,Lassen,CA,RTS,90.0,90.0,17.0,24.91,10.0,VAR,7.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
7728353,4,2019-08-23 17:01:58,40.370829,-120.400948,Susanville,Lassen,CA,RTS,90.0,90.0,17.0,24.91,10.0,VAR,7.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
7728357,3,2019-08-23 04:04:48,34.075790,-118.276680,Los Angeles,Los Angeles,CA,CQT,67.0,67.0,79.0,29.62,7.0,CALM,0.0,0.0,Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,NaN,NaN,NaN,NaN
7728361,2,2019-08-23 12:52:31,34.023790,-118.276390,Los Angeles,Los Angeles,CA,CQT,81.0,81.0,49.0,29.66,8.0,CALM,0.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
7728364,2,2019-08-23 13:42:50,34.070610,-118.263910,Los Angeles,Los Angeles,CA,CQT,82.0,82.0,47.0,29.65,9.0,CALM,0.0,0.0,Fair,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN

In [103]:
# Join missing_airport with df_airport2 on 'Airport_Code'
missing_airport_filled = missing_airport.drop(['airport_name', 'latitude', 'longitude'], axis=1, errors='ignore') \
    .merge(df_airport2, how='left', on='Airport_Code')

In [104]:
missing_airport_filled

,Severity,Start_Time,Start_Lat,Start_Lng,City,County,State,Airport_Code,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,city_name,airport_name,latitude,longitude
0,2,2016-02-08 06:49:27,39.063148,-84.032608,Williamsburg,Clermont,OH,I69,36.0,33.3,100.0,29.67,10.0,SW,3.5,NaN,Overcast,False,False,False,False,False,False,False,False,False,False,False,True,False,Night,Night,Day,Day,NaN,NaN,NaN,NaN
1,3,2016-02-08 08:14:42,39.952812,-83.119293,Columbus,Franklin,OH,TZR,35.6,30.7,93.0,29.64,5.0,WNW,5.8,NaN,Rain,False,False,True,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
2,3,2016-02-09 07:03:20,39.976398,-83.119225,Columbus,Franklin,OH,TZR,21.2,8.3,93.0,29.66,1.5,WSW,13.8,NaN,Light Snow,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day,NaN,NaN,NaN,NaN
3,2,2016-02-09 07:04:58,39.232578,-84.159286,Goshen,Clermont,OH,I69,21.0,10.6,93.0,29.73,2.5,WSW,9.2,NaN,Light Snow,False,False,False,False,False,False,False,False,False,True,False,False,False,Night,Night,Day,Day,NaN,NaN,NaN,NaN
4,2,2016-02-09 08:10:20,39.834282,-82.743820,Carroll,Fairfield,OH,LHQ,21.9,10.4,85.0,29.70,0.8,SW,11.5,0.0,Light Snow,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1808282,4,2019-08-23 17:01:58,40.374860,-120.399344,Susanville,Lassen,CA,RTS,90.0,90.0,17.0,24.91,10.0,VAR,7.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
1808283,4,2019-08-23 17:01:58,40.370829,-120.400948,Susanville,Lassen,CA,RTS,90.0,90.0,17.0,24.91,10.0,VAR,7.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
1808284,3,2019-08-23 04:04:48,34.075790,-118.276680,Los Angeles,Los Angeles,CA,CQT,67.0,67.0,79.0,29.62,7.0,CALM,0.0,0.0,Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,NaN,NaN,NaN,NaN
1808285,2,2019-08-23 12:52:31,34.023790,-118.276390,Los Angeles,Los Angeles,CA,CQT,81.0,81.0,49.0,29.66,8.0,CALM,0.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
1808286,2,2019-08-23 13:42:50,34.070610,-118.263910,Los Angeles,Los Angeles,CA,CQT,82.0,82.0,47.0,29.65,9.0,CALM,0.0,0.0,Fair,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN

In [105]:
df.update(missing_airport_filled)

In [106]:
df

,Severity,Start_Time,Start_Lat,Start_Lng,City,County,State,Airport_Code,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,airport_name,city_name,latitude,longitude
0,2,2016-02-08 06:49:27,39.063148,-84.032608,Williamsburg,Clermont,OH,I69,36.0,33.3,100.0,29.67,10.0,SW,3.5,0.02,Overcast,False,False,False,False,False,False,False,False,False,False,False,True,False,Night,Night,Day,Day,Patterson Afb,Dayton,39.826111,-84.048333
1,3,2016-02-08 08:14:42,39.952812,-83.119293,Columbus,Franklin,OH,TZR,35.6,30.7,93.0,29.64,5.0,WNW,5.8,0.00,Rain,False,False,True,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day,Port Columbus Intl,Columbus,40.000000,-82.883333
2,3,2016-02-09 07:03:20,39.976398,-83.119225,Columbus,Franklin,OH,TZR,21.2,8.3,93.0,29.66,1.5,WSW,13.8,NaN,Light Snow,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day,NaN,NaN,NaN,NaN
3,2,2016-02-09 07:04:58,39.232578,-84.159286,Goshen,Clermont,OH,I69,21.0,10.6,93.0,29.73,2.5,WSW,9.2,NaN,Light Snow,False,False,False,False,False,False,False,False,False,True,False,False,False,Night,Night,Day,Day,James Cox Dayton Intl,"Dayton, Oh",39.750000,-84.183333
4,2,2016-02-09 08:10:20,39.834282,-82.743820,Carroll,Fairfield,OH,LHQ,21.9,10.4,85.0,29.70,0.8,SW,11.5,0.00,Light Snow,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,Dayton-Wright Brothers Airport,Dayton,39.588889,-84.224722
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7728389,2,2019-08-23 18:03:25,34.002480,-117.379360,Riverside,Riverside,CA,RAL,86.0,86.0,40.0,28.92,10.0,W,13.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,Riverside Municipal,Riverside,33.950000,-117.433333
7728390,2,2019-08-23 19:11:30,32.766960,-117.148060,San Diego,San Diego,CA,MYF,70.0,70.0,73.0,29.39,10.0,SW,6.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,Montgomery Field,San Diego,32.800000,-117.133333
7728391,2,2019-08-23 19:00:21,33.775450,-117.847790,Orange,Orange,CA,SNA,73.0,73.0,64.0,29.74,10.0,SSW,10.0,0.00,Partly Cloudy,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day,John Wayne,"Santa Ana, CA",33.666667,-117.866667
7728392,2,2019-08-23 19:00:21,33.992460,-118.403020,Culver City,Los Angeles,CA,SMO,71.0,71.0,81.0,29.62,10.0,SW,8.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,Santa Monica,Santa Monica,34.015833,-118.450000
7728393,2,2019-08-23 18:52:06,34.133930,-117.230920,Highland,San Bernardino,CA,SBD,79.0,79.0,47.0,28.63,7.0,SW,7.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,Norton Afb,San Bernardino,34.095278,-117.235000

In [107]:
df[df['airport_name'].isna() & df['Airport_Code'].notna()]

,Severity,Start_Time,Start_Lat,Start_Lng,City,County,State,Airport_Code,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,airport_name,city_name,latitude,longitude
2,3,2016-02-09 07:03:20,39.976398,-83.119225,Columbus,Franklin,OH,TZR,21.2,8.3,93.0,29.66,1.5,WSW,13.8,NaN,Light Snow,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day,NaN,NaN,NaN,NaN
10,3,2016-02-10 09:03:53,40.224586,-82.929085,Galena,Delaware,OH,DLZ,17.6,5.0,79.0,29.87,3.0,West,11.5,NaN,Haze,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
53,3,2016-02-23 08:21:42,39.967640,-83.060814,Columbus,Franklin,OH,TZR,33.8,27.0,65.0,30.01,10.0,NE,8.1,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
55,2,2016-02-24 07:09:31,41.039829,-81.662872,Barberton,Summit,OH,AKR,39.9,32.5,86.0,29.59,4.0,ENE,12.7,0.22,Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
64,2,2016-02-25 06:04:05,38.892097,-84.208702,Moscow,Clermont,OH,I69,33.8,23.9,90.0,29.62,10.0,West,15.0,0.00,Overcast,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Day,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7728352,4,2019-08-23 17:01:58,40.374860,-120.399344,Susanville,Lassen,CA,RTS,90.0,90.0,17.0,24.91,10.0,VAR,7.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
7728353,4,2019-08-23 17:01:58,40.370829,-120.400948,Susanville,Lassen,CA,RTS,90.0,90.0,17.0,24.91,10.0,VAR,7.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
7728357,3,2019-08-23 04:04:48,34.075790,-118.276680,Los Angeles,Los Angeles,CA,CQT,67.0,67.0,79.0,29.62,7.0,CALM,0.0,0.00,Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,NaN,NaN,NaN,NaN
7728361,2,2019-08-23 12:52:31,34.023790,-118.276390,Los Angeles,Los Angeles,CA,CQT,81.0,81.0,49.0,29.66,8.0,CALM,0.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN
7728364,2,2019-08-23 13:42:50,34.070610,-118.263910,Los Angeles,Los Angeles,CA,CQT,82.0,82.0,47.0,29.65,9.0,CALM,0.0,0.00,Fair,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day,NaN,NaN,NaN,NaN

In [108]:
df[df['airport_name'].isna() & df['Airport_Code'].notna()]['Airport_Code'].unique()

array(['TZR', 'DLZ', 'AKR', 'I69', 'VES', 'LHQ', 'GOO', 'DVO', 'O69',
       'EDU', 'O22', 'CVH', 'E16', 'CRQ', 'CQT', '3A6', 'CMA', 'RNM',
       'NFG', 'AJO', 'F70', 'SLI', 'OKB', 'BUO', 'NXF', 'L35', 'GXA',
       'NXP', 'BKV', 'VDF', 'PMP', 'PCM', 'TTS', 'EVB', 'VVG', 'DED',
       'INF', 'CGC', 'XFL', 'XMR', 'OMN', 'RYY', '19A', 'CCO', 'EOE',
       '6A2', 'CKF', '9A1', 'FFC', 'LUX', 'CTJ', 'VPC', 'CNI', 'PUJ',
       'LHW', 'OPN', 'CWV', '27A', 'MLE', 'HNR', 'IKV', 'BTA', 'RDK',
       'ORC', 'CAV', 'PMV', 'TQE', 'IGQ', 'EFT', 'DKB', 'VLL', 'Y70',
       'OZW', 'BIV', 'LWA', 'DUH', 'D95', 'RNP', 'HYX', 'TTF', 'ONZ',
       'RQB', 'TEW', 'IKW', 'EKM', 'HWV', 'MMK', 'NYC', 'MQE', 'SMQ',
       'OQU', 'ORE', '12N', 'FWN', 'FIT', 'TAN', 'IJD', 'SNC', 'GHG',
       'VTA', 'PCW', '4I3', 'LPR', 'UNI', 'VAY', 'LOM', 'JYO', 'WBC',
       'CXY', 'DMH', 'OQN', 'DMW', 'MQS', 'OKV', 'BVI', 'NAK', 'RYT',
       'W29', 'XLL', 'HEF', 'LUA', 'UNV', '2G4', 'HMZ', 'HWY', 'AFJ',
       'FIG', 'RJD', 'FWD', 'MCJ', 'HQZ', 'FWS', 'JWY', 'LNC', 'EDC',
       'GKY', 'GPM', 'RYW', 'AXH', 'NFW', 'LVJ', 'AWN', 'TME', 'F46',
       'HYI', 'GDJ', 'BAZ', 'GTU', 'LXY', 'PWG', 'BMQ', 'UTS', 'DZB',
       '3T5', 'INJ', 'F44', 'XBP', 'JDD', 'GYB', '11R', 'T35', 'PLU',
       'AWO', '1YT', 'SMP', 'OKH', 'DEW', 'SPB', 'HRI', 'EZM', 'OXV',
       'I75', 'ARR', 'MKY', '3J7', '6A1', 'HQU', 'IIY', 'TVK', 'VTI',
       '1H2', 'PNT', '3LF', 'CFS', 'FPK', 'AQW', 'MRT', 'TRK', 'TAZ',
       'DKR', 'NSI', 'GGI', 'ADU', 'BUU', 'C09', 'AAA', '3I2', 'JES',
       'OKZ', 'RPJ', 'UUU', 'ACJ', 'GOV', 'EDJ', 'GYH', 'UZA', 'TTA',
       'MNI', 'MKS', 'FCI', 'EHO', '3A1', 'JQF', 'HYW', 'CQF', 'DYB',
       '36U', 'U42', 'BVS', 'OVL', 'EET', 'OFP', 'DTO', 'BBP', 'EQY',
       'IXD', '0E0', '79J', 'NKA', 'JNX', 'OQT', 'U24', 'LJF', 'RTS',
       'GEU', 'LXT', 'JFX', 'LHZ', 'TOB', 'VUJ', 'O87', 'HRJ', '0CO',
       'T62', 'SGJ', 'MDQ', '54J', 'LVN', 'SMS', 'FFZ', 'FDW', 'LKR',
       'CKI', 'NFE', 'MQJ', '9MN', 'RQE', 'FQD', '1F0', 'SDB', 'EBG',
       'HLX', 'AVC', 'IZG', 'DVP', 'HRT', 'IWA', 'EYE', 'TYQ', 'ASD',
       'NBC', 'HJO', 'UAO', '4A9', 'RZR', 'GPH', 'NBJ', 'PRN', 'RMN',
       'HDC', 'CFE', 'PVG', 'JZI', 'AHQ', 'MNH', 'MGG', 'RUQ', 'ANE',
       'FSW', 'FVX', 'SDL', 'AEG', 'AKH', 'TIP', 'FMM', 'IPJ', 'HXD',
       'GWB', 'POV', 'P08', 'MAO', 'DCM', 'BDU', '1P1', 'FHB', 'SEZ',
       '1V6', 'RYN', 'FYJ', 'T65', 'SGS', 'BIJ', 'VUO', 'JGG', 'ECU',
       'CMR', 'BAK', 'ROS', '40J', '3R7', 'BGF', 'C29', 'CQW', '87Q',
       '5C1', 'JXI', 'EZS', 'RGK', 'GYI', '8A0', 'EZF', 'CPK', 'MTV',
       'AUD', 'PAN', '2J9', 'CCU', 'AKQ', 'IGX', 'NCA', 'CXP', 'M16',
       '6R3', 'BDH', 'L38', 'NDZ', 'ORG', 'UDG', 'MKJ', 'DTS', 'HZR',
       '5SM', 'FYG', 'IER', 'CJR', 'EMV', 'NFJ', 'LMO', 'USE', '9A4',
       'PEO', 'HZY', 'ASG', 'GYL', 'RUE', '42J', '21D', 'ARW', 'FTG',
       'XSA', 'MMV', 'SRB', 'ETC', 'OMH', 'SFQ', 'DAW', 'JFZ', 'OXB',
       'EIK', 'VSH', 'XVG', 'B23', 'CQX', 'PNM', 'CPC', 'O86', 'DYA',
       'I39', 'TDR', 'TDF', 'LUM', 'AIT', 'SUT', 'T20', 'OXI', '5M9',
       'AJZ', 'AAO', '0J4', 'SXT', '1A5', 'IZA', '9L2', '9BB', 'MWK',
       'LXL', 'LCG', 'O54', 'GDP', 'GZH', 'PQL', 'MAI', 'BDN', 'Y63',
       '04W', 'ODO', 'AZE', 'HNZ', 'FWC', 'OSA', 'UXL', 'DPL', 'JYL',
       'D39', 'UCP', 'PEX', 'CBG', 'RZL', 'HBI', 'OWP', 'UKF', 'RYV',
       'M30', 'LYV', 'CRV', '4BM', 'JSV', 'MEB', 'NYL', '1II', 'BAN',
       'FKA', 'ADC', 'JNW', 'FLY', '0VG', 'IWI', 'CDJ', 'EXX', '14Y',
       '04V', 'GXF', 'VBT', 'LKU', 'GGP', 'ORB', 'H21', 'PCZ', 'BUY',
       'IXA', 'JYG', 'DYT', '4A6', 'U28', 'FOT', 'IBM', 'ACQ', 'NID',
       'GWW', 'AJG', 'M89', 'UTA', 'CAG', '6B0', 'LZK', 'TVR', '1M4',
       'CVB', '0A9', 'SIF', 'NMM', 'SAZ', 'PVJ', '5T6', 'MAN', 'P68',
       'CWC', 'CQB', 'S47', 'RCZ', 'OJA', '2W6', 'HSA', 'PWC', 'GZL',
       'VTP', 'LLQ', '1A6', 'EKQ', 'DDH', 'AEJ', 'FSE', 'GBN', 'JYR',
       'LBX', 'VER', 'DZJ', 'FZY', 'N03', 'GEZ', 'HZX', 'CWN', 'COQ',
       'EHR', 'AAT', 'GDB', 'GCM', 'TKC', 'JKJ', 'ANK', 'FFX', 'ONX',
       'ELO', 'Y50', 'LHX', 'PPQ', 'C75', 'AIG', '4BL', 'AZC', 'RCM',
       'CPW', 'HCD', 'F05', 'M25', 'MZH', 'BCK', 'RHP', '77M', 'ITR',
       'AFP', 'MEH', '01M', 'AMG', '5W8', 'ASW', 'STF', 'BPG', 'JMR',
       'P38', 'MNE', '4HV', 'SYF', 'HJH', '48I', '33V', '1V4', 'AQP',
       'MRJ', 'U31', 'HEQ', 'EUL', 'CPT', 'MDZ', 'NJM', 'GEV', 'DYR',
       'FSO', 'PPO', 'DCY', 'SHL', 'FNB', 'IIB', 'BEA', 'CDA', 'CKP',
       'HFJ', 'HHF', 'CUL', 'AFK', '6R6', 'VWU', 'PDC', 'IOB', 'LWD',
       'ALK', 'CQV', '2DP', 'CQM', 'SFY', 'M40', 'Y51', 'PUM', 'TNB',
       'ASJ', 'XVW', 'MYP', 'DRC', '7R3', 'ABH', 'CQC', 'GHW', '20V',
       'RPD', 'SOA', 'RBO', '1R7', '82V', '4CR', 'ARL', 'GNC', 'P58',
       'TQH', 'IYA', 'RQO', 'PZQ', 'DUX', 'GKJ', 'JKA', 'LZZ', 'T82',
       'LUD', '1J0', 'C35', 'PBH', 'BKN', 'DQH', 'DVK', 'ARM', 'ANJ',
       'RFI', 'SET', 'FZG', '2I0', 'E80', 'RNV', 'CTD', 'OLZ', 'AQV',
       'AUH', 'PQN', 'JER', 'JSO', 'SDA', 'MWT', 'LBR', 'EHY', 'CMS',
       'VDW', 'APY', 'FWB', 'HRX', 'P69', 'BKS', 'AWG', 'UNO', 'SPL',
       'K22', 'Y23', 'M46', 'SRE', 'FTN', 'GMJ', 'BBG', 'AQR', 'NOG',
       'PVB', '3DU', 'BHK', 'UKL', 'SRR', 'AQO', 'RPH', 'RSV', 'RIM',
       '08D', 'TKV', 'PIL', 'GAO', 'BQP', 'GIC', 'W22', 'PEZ', 'BRX',
       'JYM', 'BYY', 'IKA', 'PEA', 'BVN', 'AXA', 'RCX', 'BPK', 'RZN',
       'FKS', 'EYF', 'LNL', 'W99', 'MGN', 'JKL', 'ERY', 'HOE', 'OVS',
       'IDV', 'DIJ', 'E33', 'SKX', 'GPI', 'EPZ', 'HMM', 'S14', 'OEB',
       'HND', 'MLP', 'SZT', 'HBV', 'CHJ', '3TH', 'ADH', 'FOZ', 'U78',
       'MEZ', 'OCQ', 'SLH', 'SPD', 'JWG', 'HHW', 'E11', '2V5', 'I16',
       'EHA', 'W43', 'BWP', 'DEQ', '20U', '8S0', '3HT', 'Y19', 'GTB',
       '65S', 'BAC', 'WEY', 'PSO', 'S25', 'PIN', 'M19', 'D60', 'SIB',
       '3MW', '4M9', 'CNC', 'EEO', 'HCO', '4MR', 'D57', 'PRG', 'DXX',
       'BPP', 'MKN', 'GAF', 'P28', 'P67', '0F2', 'GWR', 'UNR', 'EFC',
       'S32', '5H4', '4SL', '7L2', 'PYX', 'RUG', 'PKV', 'D50', 'CUT',
       'BFW', '2WX', 'TIF', 'CVX', 'AWH', 'SAW', '2D5', '46D', 'HDO',
       'HZE', 'HEI', 'NBT', 'UBE', 'ODX', 'HSE', 'GOP', 'T43', '9V9',
       'MDS', '06D', '9D7', 'NKT', 'BVR', 'N60', 'VVV', 'MWN', 'TWM',
       'GNA', 'GNR', 'MTR', 'TBX', 'FVE', 'AVK', 'RVS', 'HUA', 'DCU',
       'MXF', 'BAD', 'DMA', 'MTC', 'MJX', 'TIX', 'TPF', 'SPG', 'COF',
       'NIP', 'LCQ', 'CSG', 'OFF', 'NPA', 'ECP', 'TKI', 'CWF', 'RMY',
       'IAB', 'DSV', 'ROX', 'I35', 'GSB', 'COE', 'RXE', 'GCD', 'TXK',
       'BAF', 'MUL', 'BAB', 'ASL', 'SKA', 'NGP', 'D25', 'VKS', 'E38',
       'ISQ', 'NQX', 'BVU', 'MVY', '7R5', 'TMK', 'TMH', 'GLY', 'SGE',
       'ACP', '4O4', 'PNA', 'RWV', 'CNB', 'MRH', 'LLJ', 'SNT', 'DUB',
       'SHC', '2C8', 'D55', 'ETH', 'AXO', 'PAT', 'IEN', '8D3', 'P53',
       'DWX', 'Y22', 'ICR'], dtype=object)

In [111]:
len(dd)

758